[package]
name = "lucky_sevens"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8.4"
rust_decimal = "1.23"
rust_decimal_macros = "1.23"